name: fiver
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ## DI
  get_it: ^7.6.4

  ## State-Management
  provider: ^6.0.5

  ## Local Database
  shared_preferences: ^2.2.1
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  ## Notification
  flutter_local_notifications: ^15.1.1

  ## Rest API
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  json_serializable: ^6.7.1

  ## UI
  go_router: ^10.1.2
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.4
  flutter_keyboard_visibility: ^5.4.1
  like_button: ^2.0.5
  intl: ^0.18.0
  flutter_image_compress: ^2.1.0

  ## common
  google_sign_in: ^6.1.5
  event_bus: ^2.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  uuidv6: ^1.0.0+1
  collection: ^1.17.2
  flutter_launcher_icons: ^0.13.1
  
  ## device settings
  permission_handler: ^11.0.1
  app_settings: ^5.1.1
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  ## media
  flutter_svg: ^2.0.9
  photo_manager: ^3.0.0-dev.2
  image_picker: ^1.0.5
  open_filex: ^4.3.4
  customize_picker:
    git:
      url: https://github.com/IMD246/CustomizePicker
      path: packages/customize_picker
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0

  ## firebase
  firebase_crashlytics: ^3.4.3
  firebase_core: ^2.21.0
  firebase_dynamic_links: ^5.4.3
  firebase_analytics: ^10.6.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
